# Task 1:

# 1.

# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def exception_handling():
    try:
        deno = int(input('Enter Denominator:'))
        ans = 5/deno
    except Exception as error:
        print('Found Error')
        print(error)
    else:
        print('Answer is %0.2f' %ans)
        
exception_handling()

Enter Denominator: 0


Found Error
division by zero


# 2.

# Implement a Python program to generate all sentences where 
# subject is in ["Americans","Indians"] and 
# verb is in ["Play", "watch"] and 
# the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
 subjects = ["Americans ","Indians"]\
 verbs = ["play","watch"]\
 objects = ["Baseball","Cricket"]

# Output should come as below:
 Americans play Baseball.\
 Americans play Cricket.\
 Americans watch Baseball.\
 Americans watch Cricket.\
 Indians play Baseball.\
 Indians play Cricket.\
 Indians watch Baseball.\
 Indians watch Cricket.

In [3]:
subjects = ['Americans','Indians']
verbs = ['play','watch']
objects = ['Baseball','Cricket']
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            print('%s %s %s.' %(subjects[i],verbs[j],objects[k]))

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

# 1.

# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

In [1]:
import numpy as np
size = int(input("Enter the size of values:"))
lis = []
for i in range(size):
    val = int(input("Enter the value"))
    lis.append(val)
arr = np.array(lis) 
mat = np.column_stack([arr**(size-i-1) for i in range(size)]) 
print(mat)

Enter the size of values:5
Enter the value1
Enter the value2
Enter the value3
Enter the value4
Enter the value5
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
